//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMSAlerts.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EAM_NL_TESTEntities1 : DbContext
    {
        public EAM_NL_TESTEntities1()
            : base("name=EAM_NL_TESTEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<R5PERSONNEL> R5PERSONNEL { get; set; }
        public virtual DbSet<R5PERSONNELQUALIFICATIONS> R5PERSONNELQUALIFICATIONS { get; set; }
    }
}
