//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMSAlerts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R5PERSONNEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public R5PERSONNEL()
        {
            this.R5PERSONNELQUALIFICATIONS = new HashSet<R5PERSONNELQUALIFICATIONS>();
            this.R5PERSONNEL1 = new HashSet<R5PERSONNEL>();
        }
    
        public string PER_CODE { get; set; }
        public string PER_DESC { get; set; }
        public string PER_CLASS { get; set; }
        public string PER_MRC { get; set; }
        public string PER_TRADE { get; set; }
        public string PER_NOTUSED { get; set; }
        public Nullable<decimal> PER_CAPACITY { get; set; }
        public string PER_ORG { get; set; }
        public string PER_CLASS_ORG { get; set; }
        public string PER_EMAILADDRESS { get; set; }
        public string PER_NOTIFICATIONPREF { get; set; }
        public string PER_USER { get; set; }
        public Nullable<System.DateTime> PER_CREATED { get; set; }
        public string PER_CREATEDBY { get; set; }
        public Nullable<System.DateTime> PER_UPDATED { get; set; }
        public string PER_UPDATEDBY { get; set; }
        public Nullable<decimal> PER_UPDATECOUNT { get; set; }
        public int PER_SQLIDENTITY { get; set; }
        public string PER_FLEETCUSTOMER { get; set; }
        public string PER_FLEETCUSTOMER_ORG { get; set; }
        public string PER_COSTCODE { get; set; }
        public string PER_DRIVERSLICENSE { get; set; }
        public string PER_PHONE { get; set; }
        public string PER_PARENT { get; set; }
        public string PER_SCHEDULINGSESSIONID { get; set; }
        public string PER_SCHEDULINGTYPE { get; set; }
        public string PER_CUSTOMER { get; set; }
        public string PER_CUSTOMER_ORG { get; set; }
        public string PER_ALIAS { get; set; }
        public string PER_OBJECT { get; set; }
        public string PER_OBJECT_ORG { get; set; }
        public string PER_UDFCHAR01 { get; set; }
        public string PER_UDFCHAR02 { get; set; }
        public string PER_UDFCHAR03 { get; set; }
        public string PER_UDFCHAR04 { get; set; }
        public string PER_UDFCHAR05 { get; set; }
        public string PER_UDFCHAR06 { get; set; }
        public string PER_UDFCHAR07 { get; set; }
        public string PER_UDFCHAR08 { get; set; }
        public string PER_UDFCHAR09 { get; set; }
        public string PER_UDFCHAR10 { get; set; }
        public string PER_UDFCHAR11 { get; set; }
        public string PER_UDFCHAR12 { get; set; }
        public string PER_UDFCHAR13 { get; set; }
        public string PER_UDFCHAR14 { get; set; }
        public string PER_UDFCHAR15 { get; set; }
        public string PER_UDFCHAR16 { get; set; }
        public string PER_UDFCHAR17 { get; set; }
        public string PER_UDFCHAR18 { get; set; }
        public string PER_UDFCHAR19 { get; set; }
        public string PER_UDFCHAR20 { get; set; }
        public string PER_UDFCHAR21 { get; set; }
        public string PER_UDFCHAR22 { get; set; }
        public string PER_UDFCHAR23 { get; set; }
        public string PER_UDFCHAR24 { get; set; }
        public string PER_UDFCHAR25 { get; set; }
        public string PER_UDFCHAR26 { get; set; }
        public string PER_UDFCHAR27 { get; set; }
        public string PER_UDFCHAR28 { get; set; }
        public string PER_UDFCHAR29 { get; set; }
        public string PER_UDFCHAR30 { get; set; }
        public Nullable<decimal> PER_UDFNUM01 { get; set; }
        public Nullable<decimal> PER_UDFNUM02 { get; set; }
        public Nullable<decimal> PER_UDFNUM03 { get; set; }
        public Nullable<decimal> PER_UDFNUM04 { get; set; }
        public Nullable<decimal> PER_UDFNUM05 { get; set; }
        public Nullable<System.DateTime> PER_UDFDATE01 { get; set; }
        public Nullable<System.DateTime> PER_UDFDATE02 { get; set; }
        public Nullable<System.DateTime> PER_UDFDATE03 { get; set; }
        public Nullable<System.DateTime> PER_UDFDATE04 { get; set; }
        public Nullable<System.DateTime> PER_UDFDATE05 { get; set; }
        public string PER_UDFCHKBOX01 { get; set; }
        public string PER_UDFCHKBOX02 { get; set; }
        public string PER_UDFCHKBOX03 { get; set; }
        public string PER_UDFCHKBOX04 { get; set; }
        public string PER_UDFCHKBOX05 { get; set; }
        public string PER_JOBTITLE { get; set; }
        public string PER_SUPERVISOR { get; set; }
        public Nullable<System.DateTime> PER_HIREDATE { get; set; }
        public Nullable<System.DateTime> PER_BIRTHDATE { get; set; }
        public Nullable<System.DateTime> PER_TERMINATEDDATE { get; set; }
        public string PER_PAYROLLNO { get; set; }
        public string PER_SECURITYBADGENO { get; set; }
        public string PER_ADDRESS { get; set; }
        public string PER_CITY { get; set; }
        public string PER_STATE { get; set; }
        public string PER_ZIP { get; set; }
        public string PER_COUNTRY { get; set; }
        public string PER_EMERGENCYCONTACT { get; set; }
        public string PER_EMERGENCYCONTACTPHNO { get; set; }
        public string PER_MOBILEPHONENO { get; set; }
        public string PER_HOMEPHONENO { get; set; }
        public string PER_URL { get; set; }
        public string PER_FAX { get; set; }
        public string PER_INITIALS { get; set; }
        public string PER_TRADESPERSON { get; set; }
        public string PER_WORKSPACEOCCUPANT { get; set; }
        public Nullable<System.DateTime> PER_LASTSAVED { get; set; }
        public string PER_PROFILEPICTURE { get; set; }
        public string PER_DETERMINESCREWLOCATION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R5PERSONNELQUALIFICATIONS> R5PERSONNELQUALIFICATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R5PERSONNEL> R5PERSONNEL1 { get; set; }
        public virtual R5PERSONNEL R5PERSONNEL2 { get; set; }
    }
}
