//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMSAlerts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R5PERSONNELQUALIFICATIONS
    {
        public string PQU_PERSON { get; set; }
        public string PQU_QUALIFICATION { get; set; }
        public string PQU_PURPOSE { get; set; }
        public Nullable<decimal> PQU_HOURS { get; set; }
        public Nullable<decimal> PQU_CEU { get; set; }
        public Nullable<System.DateTime> PQU_COURSESTART { get; set; }
        public Nullable<System.DateTime> PQU_COURSEFINISH { get; set; }
        public Nullable<decimal> PQU_COURSECOST { get; set; }
        public string PQU_CURRENCY { get; set; }
        public string PQU_COURSECOMPLETED { get; set; }
        public string PQU_CERTIFICATION { get; set; }
        public string PQU_CERTIFICATIONTYPE { get; set; }
        public System.DateTime PQU_QUALIFICATIONSTART { get; set; }
        public Nullable<decimal> PQU_DURATION { get; set; }
        public string PQU_DURATIONUOM { get; set; }
        public Nullable<System.DateTime> PQU_EXPIRATION { get; set; }
        public string PQU_COMMENTS { get; set; }
        public string PQU_TEMPDISQUALIFIED { get; set; }
        public Nullable<System.DateTime> PQU_UPDATED { get; set; }
        public Nullable<decimal> PQU_UPDATECOUNT { get; set; }
        public int PQU_SQLIDENTITY { get; set; }
        public Nullable<System.DateTime> PQU_LASTSAVED { get; set; }
    
        public virtual R5PERSONNEL R5PERSONNEL { get; set; }
    }
}
